import { writeFileSync, chmodSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';

/**
 * PreToolUse gating happens at the runner, not in the prompt. A prompt-level
 * rule is a suggestion; a hook is a gate. Claude runs this script before every
 * tool call, it asks the Switchboard gateway what to do, and blocks until it
 * gets an answer (a confirm can take as long as the human takes to reply).
 *
 * Contract (Claude Code hooks): read JSON from stdin, write a JSON decision to
 * stdout, exit 0. Exit 2 also blocks, with stderr fed back to the model.
 */
const HOOK_SOURCE = String.raw`#!/usr/bin/env node
// Generated by Switchboard. Do not edit — regenerated on every daemon start.
import { request } from 'node:http';

const ENDPOINT = process.env.SWB_HOOK_URL;
const RUN_ID = process.env.SWB_RUN_ID;
const TOKEN = process.env.SWB_HOOK_TOKEN || '';

function readStdin() {
  return new Promise((resolve) => {
    let buf = '';
    process.stdin.setEncoding('utf8');
    process.stdin.on('data', (c) => (buf += c));
    process.stdin.on('end', () => resolve(buf));
  });
}

function ask(payload) {
  return new Promise((resolve) => {
    const body = JSON.stringify(payload);
    const url = new URL(ENDPOINT);
    const req = request(
      {
        hostname: url.hostname,
        port: url.port,
        path: url.pathname,
        method: 'POST',
        headers: {
          'content-type': 'application/json',
          'content-length': Buffer.byteLength(body),
          authorization: 'Bearer ' + TOKEN,
        },
        // A confirm-by-reply can legitimately take many minutes.
        timeout: 0,
      },
      (res) => {
        let out = '';
        res.setEncoding('utf8');
        res.on('data', (c) => (out += c));
        res.on('end', () => {
          try {
            resolve(JSON.parse(out));
          } catch {
            resolve({ decision: 'deny', reason: 'switchboard gateway returned malformed JSON' });
          }
        });
      },
    );
    req.on('error', (err) => resolve({ decision: 'deny', reason: 'switchboard gateway unreachable: ' + err.message }));
    req.write(body);
    req.end();
  });
}

const raw = await readStdin();
let input = {};
try {
  input = JSON.parse(raw || '{}');
} catch {
  input = {};
}

// Fail closed: with no gateway configured we cannot gate, so we refuse.
if (!ENDPOINT || !RUN_ID) {
  process.stdout.write(
    JSON.stringify({
      hookSpecificOutput: {
        hookEventName: 'PreToolUse',
        permissionDecision: 'deny',
        permissionDecisionReason: 'Switchboard gating is not configured for this run.',
      },
    }),
  );
  process.exit(0);
}

const verdict = await ask({
  runId: RUN_ID,
  tool: input.tool_name,
  input: input.tool_input || {},
  sessionId: input.session_id,
  cwd: input.cwd,
});

const decision = verdict.decision === 'allow' ? 'allow' : verdict.decision === 'ask' ? 'ask' : 'deny';
process.stdout.write(
  JSON.stringify({
    hookSpecificOutput: {
      hookEventName: 'PreToolUse',
      permissionDecision: decision,
      permissionDecisionReason: verdict.reason || 'Switchboard policy',
    },
  }),
);
process.exit(0);
`;

export interface HookSetup {
  scriptPath: string;
  settingsPath: string;
}

/** Write the hook script plus a settings file that wires it to PreToolUse. */
export function installHook(dataDir: string): HookSetup {
  const scriptPath = join(dataDir, 'hooks', 'pretooluse.mjs');
  mkdirSync(dirname(scriptPath), { recursive: true });
  writeFileSync(scriptPath, HOOK_SOURCE);
  chmodSync(scriptPath, 0o755);

  const settingsPath = join(dataDir, 'hooks', 'settings.json');
  const settings = {
    hooks: {
      PreToolUse: [
        {
          matcher: '*',
          hooks: [{ type: 'command', command: `node ${scriptPath}`, timeout: 86_400 }],
        },
      ],
    },
  };
  writeFileSync(settingsPath, `${JSON.stringify(settings, null, 2)}\n`);
  return { scriptPath, settingsPath };
}

export const HOOK_PATH = '/hook/pretooluse';
